### ISSUE TITLE
Tracking issue: Feature completeness

### ISSUE THREAD

**Issue by vbe0201** [mirage-rs/libtegra#2]
This is a tracking issue for the features of this library.

## The TRM

The Tegra X1 Technical Reference Manual (TRM), along with the `tegra210` drivers in the Linux kernel are probably the most complete and detailed sources of documentation of Tegra X1 SoC functionality out there. (Beware: Both are bad, but one better than the other!)

The TRM can be obtained from [NVIDIA's download center](https://developer.nvidia.com/embedded/downloads) as `Tegra X1 (SoC) Technical Reference Manual` as soon as you've created an account for free. It documents most hardware capabilities, which is a good starting point for new drivers.

## Implementation Guidelines

* Fundamentally, it is expected that registers are wrapped through [register-rs](https://github.com/rust-embedded/register-rs) and exposed.
  * Even if actual logic can't be implemented due to the lack of knowledge/documentation, users have the possibility to do that themselves.
  * An abstract driver implementation may not fit the needs of the user, giving them full control over what they are trying to achieve.

* On top of the registers, a reference implementation of a driver can be built.
  * It is expected that the core functionality of a device is exposed.
  * These implementations should provide a safe and easy-to-use API for interfacing with the hardware.
  * Code is expected to be well-documented so readers can understand the logic and purpose behind it.

## Features

* [x] `2. Address and Interrupt Map`

* [x] `3. Interrupt Controller`

* [ ] `4. Semaphores`

* [x] `5. Clock and Reset Controller`

* [ ] `6. CL-DVFS`

* [x] `7. Atomics`

* [x] `8. Timers`

* [x] `9. Multi-Purpose I/O Pins and Pin Multiplexing (Pinmux)`

* [x] `10. Activity Monitor`

* [x] `11. Real-Time Clock`

* [x] `12. Power Management Controller`

* [x] `13. Boot Process` *(WIP)*
  * Fuses

* [ ] `14. Host Subsystem`

* [x] `15. Video Image Compositor (VIC)`

* [ ] `16. CPU Complex`

* [x] `17. Flow Controller`

* [x] `18. Memory Controller`

* [x] `19. AHB`

* [x] `21. APB`

* [ ] `22. USB Complex`

* [ ] `23. Audio Processing Engine`

* [ ] `24. Display Controller`

* [ ] `25. Color Decompression Engine`

* [ ] `26./27. Display Interfaces`

* [ ] `28. HDMI CEC`

* [ ] `29./30. MIPI-CSI`

* [ ] `31. Video Input (VI)`

* [ ] `32. SD/MMC Controller`

* [ ] `33. SATA Controller`

* [ ] `34. PCI Express Controller`

* [x] `35. I2C Controller`

* [x] `36. UART Controller`

* [x] `37. Serial Peripheral Interface (SPI) Controller` *(WIP)*

* [x] `38. Quad Serial Peripheral Interface (QSPI) Controller` *(WIP)*

* [x] `39. PWM Controller`

* [x] `41. Boot and Power Management Processor-Lite`

* [ ] `42. CoreSight (Debugging)`

Not mentioned on the TRM but also relevant:

* [x] `Tegra Security Co-Processor (TSEC)`

* [x] `Security Engine (SE)`

* [ ] `NVHOST`
